-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-23 10:41:34 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE category (
    cut VARCHAR2(250) NOT NULL
);

ALTER TABLE category ADD CONSTRAINT category_pk PRIMARY KEY ( cut );

CREATE TABLE clarity (
    clarity VARCHAR2(250) NOT NULL
);

ALTER TABLE clarity ADD CONSTRAINT clarity_pk PRIMARY KEY ( clarity );

CREATE TABLE color (
    color VARCHAR2(250) NOT NULL
);

ALTER TABLE color ADD CONSTRAINT color_pk PRIMARY KEY ( color );

CREATE TABLE customer (
    id                            VARCHAR2(250) NOT NULL,
    customer_name                 VARCHAR2(250),
    person_name                   VARCHAR2(250),
    ring_ring_index               INTEGER NOT NULL,
    ring_diamond_diamond_index    INTEGER NOT NULL,
    ring_diamond_category_cut     VARCHAR2(250) NOT NULL,
    ring_diamond_clarity_clarity  VARCHAR2(250) NOT NULL,
    ring_diamond_color_color      VARCHAR2(250) NOT NULL
);

CREATE UNIQUE INDEX customer__idx ON
    customer (
        ring_ring_index
    ASC,
        ring_diamond_diamond_index
    ASC,
        ring_diamond_category_cut
    ASC,
        ring_diamond_clarity_clarity
    ASC,
        ring_diamond_color_color
    ASC );

ALTER TABLE customer
    ADD CONSTRAINT customer_pk PRIMARY KEY ( id,
                                             ring_ring_index,
                                             ring_diamond_diamond_index,
                                             ring_diamond_category_cut,
                                             ring_diamond_clarity_clarity,
                                             ring_diamond_color_color );

CREATE TABLE diamond (
    diamond_index    INTEGER NOT NULL,
    carat_weight     VARCHAR2(10),
    category_cut     VARCHAR2(250) NOT NULL,
    clarity_clarity  VARCHAR2(250) NOT NULL,
    color_color      VARCHAR2(250) NOT NULL
);

ALTER TABLE diamond
    ADD CONSTRAINT diamond_pk PRIMARY KEY ( diamond_index,
                                            category_cut,
                                            clarity_clarity,
                                            color_color );

CREATE TABLE ring (
    ring_index               INTEGER NOT NULL,
    diamond_diamond_index    INTEGER NOT NULL,
    diamond_category_cut     VARCHAR2(250) NOT NULL,
    diamond_clarity_clarity  VARCHAR2(250) NOT NULL,
    diamond_color_color      VARCHAR2(250) NOT NULL
);

CREATE UNIQUE INDEX ring__idx ON
    ring (
        diamond_diamond_index
    ASC,
        diamond_category_cut
    ASC,
        diamond_clarity_clarity
    ASC,
        diamond_color_color
    ASC );

ALTER TABLE ring
    ADD CONSTRAINT ring_pk PRIMARY KEY ( ring_index,
                                         diamond_diamond_index,
                                         diamond_category_cut,
                                         diamond_clarity_clarity,
                                         diamond_color_color );

ALTER TABLE customer
    ADD CONSTRAINT customer_ring_fk FOREIGN KEY ( ring_ring_index,
                                                  ring_diamond_diamond_index,
                                                  ring_diamond_category_cut,
                                                  ring_diamond_clarity_clarity,
                                                  ring_diamond_color_color )
        REFERENCES ring ( ring_index,
                          diamond_diamond_index,
                          diamond_category_cut,
                          diamond_clarity_clarity,
                          diamond_color_color );

ALTER TABLE diamond
    ADD CONSTRAINT diamond_category_fk FOREIGN KEY ( category_cut )
        REFERENCES category ( cut );

ALTER TABLE diamond
    ADD CONSTRAINT diamond_clarity_fk FOREIGN KEY ( clarity_clarity )
        REFERENCES clarity ( clarity );

ALTER TABLE diamond
    ADD CONSTRAINT diamond_color_fk FOREIGN KEY ( color_color )
        REFERENCES color ( color );

ALTER TABLE ring
    ADD CONSTRAINT ring_diamond_fk FOREIGN KEY ( diamond_diamond_index,
                                                 diamond_category_cut,
                                                 diamond_clarity_clarity,
                                                 diamond_color_color )
        REFERENCES diamond ( diamond_index,
                             category_cut,
                             clarity_clarity,
                             color_color );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             2
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

--Завдання на тригер: Не дозволяє змінити колір купленого діаманту
CREATE OR REPLACE TRIGGER customer_color_trigger
    BEFORE UPDATE
    OF ring_diamond_color_color ON customer
    FOR EACH ROW
    BEGIN
        :new.ring_diamond_color_color := :old.ring_diamond_color_color;
    END;
